### ISSUE TITLE
BUG on prices on BTC. Can not handle more than 2 decimals, i need 4 decimals.

### ISSUE THREAD

**Issue by Lbenza** [cryptoapi/Bitcoin-Gateway-Paid-Memberships-Pro#1]
Hi! I put the membership prices in BTC and i can not handle payments for more than 2 decimals.

For example my membership value is 0.015 and when i press save, automatically get save as 0.02

How can i fix this? thanks

**Comment by Lbenza** [comment]
![captura de pantalla 2017-11-20 a las 14 44 36](https://user-images.githubusercontent.com/25757196/33033008-c3a76b66-ce01-11e7-807b-2f0883601897.png)

**Comment by Lbenza** [comment]
Really this problem because BTC keep rising in price.

**Comment by cryptoapi** [comment]
you need to place this request on PMPro forum https://wordpress.org/plugins/paid-memberships-pro/
It is PMPro  main config screen and we cannot do nothing in this sitation. We provide only payment  addon to PMPro .
