### ISSUE TITLE
Define the number of decimals to use when setting up the currency for PMPro

### ISSUE THREAD

**Issue by ideadude** [cryptoapi/Bitcoin-Gateway-Paid-Memberships-Pro#2]
PMPro now allows you to set the number of decimals when defining a currency. Here is an example in the core plugin setting the decimal to 0 for yen:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/currencies.php#L51

You could similarly define btc with 8 decimal places here:
https://github.com/cryptoapi/Bitcoin-Gateway-Paid-Memberships-Pro/blob/master/gourl_paidmembershipspro.php#L186

**Comment by cryptoapi** [comment]
We added https://github.com/cryptoapi/Bitcoin-Gateway-Paid-Memberships-Pro/blob/master/gourl_paidmembershipspro.php#L193

but "Initial Payment:" value on PMPro settings page still support 2 decimals only.
