### ISSUE TITLE
Call back issue

### ISSUE THREAD

**Issue by bitcoinbrisbane** [cryptoapi/Bitcoin-Gateway-Paid-Memberships-Pro#4]
Getting error and memberships are not getting marked as paid.

Your Bitcoin Box : #6043

TxID: f705f8afd9efba3fb138b7a4757b5fa507ae24e134e9b06b4e1a342f4ae3eb9d  (order: gourlpmpro.order149)

Your IPN Url: https://blockchainaustralia.org?cryptobox.callback.php

It should return in plain text - 'cryptobox_newrecord' or 'cryptobox_updated' or 'cryptobox_nochanges' to GoUrl server only.

------output start------------ 

MySQL Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'processedDate' at row 1; SQL: INSERT INTO crypto_payments (boxID, boxType, orderID, userID, countryID, coinLabel, amount, amountUSD, unrecognised, addr, txID, txDate, txConfirmed, txCheckDate, recordCreated) VALUES (6043, 'paymentbox', 'gourlpmpro.order149', 'user166', 'USA', 'BTC', 0.01739714, 61.65, 0, '1PgpML2yY8FYTRB56JGfCjRmXyYJMpVzgc', 'f705f8afd9efba3fb138b7a4757b5fa507ae24e134e9b06b4e1a342f4ae3eb9d', '2019-02-15 01:37:12', 1, '2019-02-15 02:42:04', '2019-02-15 02:42:04') 

------output end------------

**Comment by cryptoapi** [comment]
You can check your sql mode by executing this:

`SELECT @@sql_mode;`
and if any of the NO_ZERO_DATE or NO_ZERO_IN_DATE are set, then you can just:

`SET sql_mode = '';`


https://stackoverflow.com/questions/40425568/incorrect-datetime-value-0000-00-00-000000-date-sub-in-having
